---
version: 2
jobs:
  # Build recent stable Linux kernel, with no patches
  vanilla:
    machine:
      image: ubuntu-2004:202010-01
    # Can't use volume mounts in CircleCI with docker driver
    # docker:
    #   - image: circleci/python:buster
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y make build-essential
      - run: make vanilla
  # Run reprotest to confirm reproducible builds
  reproducibility:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y make build-essential reprotest
      - run: make reprotest

  reproducibility-securedrop:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y make build-essential reprotest
      - run:
          name: Build SecureDrop kernel reproducibly
          command: make reprotest-sd
          # The linux-image-debug package step takes >30m
          no_output_timeout: 60m
workflows:
  version: 2
  build:
    jobs:
      - vanilla
      - reproducibility
      # SD test build exceeds CircleCI timeout of 5h (~2.5h x2 for reproducibility),
      # so it'll never pass. With a leaner config, it likely would.
      # - reproducibility-securedrop
