#!/bin/bash

set -e
set -u
set -o pipefail


# SOURCE_DATE_EPOCH="$(git log -1 --pretty=%ct)"
# DEBUG: setting constant value to make eval easier
SOURCE_DATE_EPOCH="1309379017"
export SOURCE_DATE_EPOCH
export KBUILD_BUILD_TIMESTAMP="@${SOURCE_DATE_EPOCH}"
export DEB_BUILD_TIMESTAMP="${SOURCE_DATE_EPOCH}"

local_config_volume_opt=""
if [[ -n "${LINUX_LOCAL_CONFIG_PATH:-}" ]]; then
    local_config_volume_opt="-v ${LINUX_LOCAL_CONFIG_PATH}:/config:ro"
fi
local_patches_volume_opt=""
if [[ -n "${LINUX_LOCAL_PATCHES_PATH:-}" ]]; then
    local_patches_volume_opt="-v ${LINUX_LOCAL_PATCHES_PATH}:/patches:ro"
fi

img_name="quay.io/conorsch/kernel-builder"
kernel_dir="$PWD/build"
mkdir -p -m 755 "$kernel_dir"
docker build -t "$img_name" \
    --build-arg USERNAME="$USER" \
    --build-arg UID="$(id -u)" \
    --build-arg GID="$(id -g)" \
    .

docker run --rm -t \
    -e GRSECURITY_USERNAME \
    -e GRSECURITY_PASSWORD \
    -e GRSECURITY_PATCH_TYPE \
    -e GRSECURITY \
    -e SOURCE_DATE_EPOCH \
    -e KBUILD_BUILD_TIMESTAMP \
    -e DEB_BUILD_TIMESTAMP \
    -e LOCALVERSION \
    -v "${kernel_dir}:/output" \
    $local_config_volume_opt \
    $local_patches_volume_opt \
    "$img_name"

echo "Build complete. Packages can be found at:"
find "$kernel_dir" -type f | sort
