#!/bin/bash

set -e
set -u
set -o pipefail


# SOURCE_DATE_EPOCH="$(git log -1 --pretty=%ct)"
# DEBUG: setting constant value to make eval easier
SOURCE_DATE_EPOCH="1309379017"
export SOURCE_DATE_EPOCH
export KBUILD_BUILD_TIMESTAMP="@${SOURCE_DATE_EPOCH}"
export DEB_BUILD_TIMESTAMP="${SOURCE_DATE_EPOCH}"
export TERM=dumb  # to omit control characters from "script" transcripts
export BUILD_DISTRO="${BUILD_DISTRO:-bookworm}"

# Build container image for kernel dependencies
IMG_NAME="fpf.local/kernel-builder"
docker build -t "${IMG_NAME}-${BUILD_DISTRO}" \
    --build-arg UID="$(id -u)" \
    --build-arg GID="$(id -g)" \
    --build-arg BUILD_DISTRO="$BUILD_DISTRO" \
    .

# Configure local customizations
local_config_volume_opt=""
if [[ -n "${LINUX_LOCAL_CONFIG_PATH:-}" ]]; then
    local_config_volume_opt="-v ${LINUX_LOCAL_CONFIG_PATH}:/config:ro"
fi
local_patches_volume_opt=""
if [[ -n "${LINUX_LOCAL_PATCHES_PATH:-}" ]]; then
    local_patches_volume_opt="-v ${LINUX_LOCAL_PATCHES_PATH}:/patches:ro"
fi

# Create output dir
kernel_dir="$PWD/build"
mkdir -p -m 755 "$kernel_dir"

DOCKER_RUN_ARGUMENTS=""
# Pass -it if we're a tty
if test -t 0; then
    DOCKER_RUN_ARGUMENTS="${DOCKER_RUN_ARGUMENTS} -it"
fi

docker run --rm $DOCKER_RUN_ARGUMENTS \
    -e GRSECURITY_USERNAME \
    -e GRSECURITY_PASSWORD \
    -e GRSECURITY_PATCH_TYPE \
    -e GRSECURITY \
    -e SOURCE_DATE_EPOCH \
    -e KBUILD_BUILD_TIMESTAMP \
    -e DEB_BUILD_TIMESTAMP \
    -e LINUX_MAJOR_VERSION \
    -e LOCALVERSION \
    -e BUILD_VERSION \
    -e TERM \
    -v "${kernel_dir}:/output:Z" \
    $local_config_volume_opt \
    $local_patches_volume_opt \
    "${IMG_NAME}-${BUILD_DISTRO}"

echo "Build complete. Packages can be found at:"
find "$kernel_dir" -type f | sort

echo "And sha256sums are:"
find "$kernel_dir" -type f \( -name "*.deb" -o -name "*.buildinfo" -o -name "*.orig.tar.xz" \) -exec sha256sum {} \;
