#!/bin/bash
# postinst script for securedrop-workstation-grsec
#
# see: dh_installdeb(1)
set -e
set -x
# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

# Pin current version of custom kernel
GRSEC_VERSION="#DEB_VERSION_UPSTREAM#"

# Sets default grub boot parameter to the kernel version specified
# by $GRSEC_VERSION because the default bullseye kernels have
# higher versions and would supersede our grsecurity kernels.
set_grub_default() {
    GRUB_OPT="'Advanced options for Debian GNU/Linux>Debian GNU/Linux, with Linux $GRSEC_VERSION'"
    perl -pi -e "s|^GRUB_DEFAULT=.*|GRUB_DEFAULT=$GRUB_OPT|" /etc/default/grub
}

# Ensure the paxctld daemon is running
start_paxctld() {
    paxctld_config='/etc/paxctld.conf'
    if [ -f "$paxctld_config" ]; then
        systemctl enable paxctld
        systemctl restart paxctld
        # Wait just a moment while flag are re-applied
        sleep 1
    fi
}

case "$1" in
    configure)
    # Ensure pax flags are set prior to running grub
    start_paxctld
    # Force latest hardened kernel for next boot
    set_grub_default
    update-grub
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
