name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        target:
          - tiny-5.15
          - tiny-6.6
        # Build twice for comparison
        build:
          - one
          - two
    outputs:
      artifact_id: ${{ steps.upload.outputs.artifact-id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make build-essential

      - name: Build tiny kernel
        run: make ${{ matrix.target }}

      - uses: actions/upload-artifact@v4
        id: upload
        with:
          name: ${{ matrix.target }}-${{ matrix.build }}
          path: build
          if-no-files-found: error

  reproducible:
    runs-on: ubuntu-24.04
    container: debian:bookworm
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        target:
          - tiny-5.15
          - tiny-6.6
    steps:
      - name: Install dependencies
        run: |
          apt-get update && apt-get install --yes diffoscope-minimal python3-debian xz-utils \
            --no-install-recommends
      - uses: actions/download-artifact@v4
        with:
          pattern: "${{ matrix.target }}*"
      - name: diffoscope
        run: |
          # We need to exclude .buildinfo because the `Build-Date` will be different
          diffoscope ${{ matrix.target }}-one/*.changes ${{ matrix.target }}-two/*.changes --exclude '*.buildinfo'
