name: CI

on: [push, pull_request]

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    container: debian:trixie
    steps:
      - name: Bootstrap Debian system package dependencies
        run: |
          apt-get update
          apt-get install --yes --no-install-recommends \
            git \
            make \
            python3-poetry
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name:  Install additional packages and Python dependencies
        run: |
          poetry install --no-ansi
      - name: Run linters
        run: |
          make lint

  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        target:
          - tiny-6.6
        # Build twice for comparison
        build:
          - one
          - two
    outputs:
      artifact_id: ${{ steps.upload.outputs.artifact-id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make build-essential

      - name: Build tiny kernel
        run: make ${{ matrix.target }}

      - uses: actions/upload-artifact@v4
        id: upload
        with:
          name: ${{ matrix.target }}-${{ matrix.build }}
          path: build
          if-no-files-found: error

  reproducible:
    runs-on: ubuntu-latest
    container: debian:bookworm
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        target:
          - tiny-6.6
    steps:
      - name: Install dependencies
        run: |
          apt-get update && apt-get install --yes diffoscope-minimal python3-debian xz-utils \
            --no-install-recommends
      - uses: actions/download-artifact@v5
        with:
          pattern: "${{ matrix.target }}*"
      - name: diffoscope
        run: |
          # We need to exclude .buildinfo because the `Build-Date` will be different
          diffoscope ${{ matrix.target }}-one/*.changes ${{ matrix.target }}-two/*.changes --exclude '*.buildinfo'
